services:
  - type: web
    name: moviesflix-auto-download
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
